### ISSUE TITLE
RSS feed has stopped.

### ISSUE THREAD

**Issue by JoshuaCrewe** [zanshin/zanshin#13]
How does it feel to know that someone has noticed your RSS feed has stopped working ?

I use a small an [app](https://github.com/FraGag/feeds-to-pocket) to parse and RSS feed and push new feeds to my pocket. It kicked up an error a little while ago : 
```
downloading https://zanshin.net/atom.xml
failed to parse feed at https://zanshin.net/atom.xml as either RSS or Atom:
  could not parse input as either Atom or RSS:
    parsing as Atom failed with:
      Error while escaping character at range 30..37: Cannot find ';' after '&'
    parsing as RSS failed with:
      the input did not begin with an rss tag
```

Basically [https://zanshin.net/atom.xml](https://zanshin.net/atom.xml) is blank. 

Cheers!

**Comment by zanshin** [comment]
Try it now. 

There was a posting with an ampersand (&) in the title that wasn't getting properly escaped in the Atom feed.

**Comment by JoshuaCrewe** [comment]
That is beautiful.

Thanks very much!
